### PR TITLE
[WIP] Add: template for PHP OpCache

### LINKED ISSUE #4: configure OpCache
### Type of Report

feature request

### Actual behaviour

opcache is not configured

### Expected behaviour

add /etc/php.d/opcache.ini as template and configure it

### PR DESCRIPTION
**Pull request by donvipre**
# Add: template for PHP OpCache

## Reference

 - Resolves: #4

### CODE REVIEW

**Review by Cinux90 — COMMENTED** [review]
Its needed to setup the opcache.ini if the variable wtd_php_opcache_enabled is set to 0?
From my point of view this step can be skipped if opcache is not enabled. What did you think about?

**Comment by daniel-schier** [comment]
any update here?

**Comment by Cinux90** [comment]
Nearly one year since PR got created. Any update?

**Comment by daniel-schier** [comment]
@Cinux90 I am currently re-writing a lot of stuff. Maybe we can have a chat this week to align how to proceed and which steos to take. You can also have a look at the nextcloud deck to see the progress and ideas. but be aware, there is a lot to see.

**Pull request closed without merging**
